apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: remoteconfigs.operator.istio.io
spec:
  group: operator.istio.io
  names:
    kind: RemoteConfig
    plural: remoteconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterName:
              type: string
            config:
              properties:
                enabledServices:
                  items:
                    properties:
                      labelSelector:
                        type: string
                      name:
                        type: string
                      podIPs:
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - labelSelector
                    - podIPs
                    type: object
                  type: array
              required:
              - enabledServices
              type: object
          required:
          - clusterName
          - config
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
