apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-sample
spec:
  mtls: false
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  pilot:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
  citadel:
      replicaCount: 1
  galley:
      replicaCount: 1
  gateways:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
  mixer:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
  sidecarInjector:
      replicaCount: 1
