apiVersion: operator.istio.io/v1beta1
kind: RemoteConfig
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: remote-cluster
spec:
  includeIPRanges: "*"
  excludeIPRanges: ""
  enabledServices:
  - name: "istio-pilot"
    labelSelector: "istio=pilot"
  - name: "istio-policy"
    labelSelector: "istio-mixer-type=policy"
  - name: "istio-statsd"
    labelSelector: "statsd-prom-bridge"
  - name: "istio-telemetry"
    labelSelector: "istio-mixer-type=telemetry"
  - name: "zipkin"
    labelSelector: "app=jaeger"
